site_name: Raghav's Garage
site_description: "Raghav Kumar's Portfolio"

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night # Icon for light mode to switch to dark
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny # Icon for dark mode to switch to light
        name: Switch to light mode

nav:
  - Home: index.md
  - The Garage: projects.md
  - Book:
      The New Life: chapters/The New Life.md
      The Golden Downfall: chapters/The Golden Downfall.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg